[package]
name = "ratchet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
ron = "0.12.0"
regex = "1.12.2"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.8"
walkdir = "2.5.0"
seahash = "4.1.0"
